[build]
command = "pnpm install && pnpm build && mkdir -p node_modules/openai/helpers && cp node_modules/zod/lib/index.mjs node_modules/openai/helpers/zod.mjs"
publish = "build/client"

[dev]
command = "pnpm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

[[plugins]]
  package = "./netlify/plugins/fix-modules"
